### ISSUE TITLE
Create User Profile

### ISSUE THREAD

**Issue by todiane** [todiane/our-spot#1]
As a user, I want to create a profile and upload a profile picture so that others can recognize me on the platform.

**Acceptance Criteria**

- [x] 1. Create an area where I can add a profile
- [x] 2.  Provide CRUD functionalities

**Tasks**

- [x] Task 1: Set up template to add information
- [x] Task 2: Set up ability to edit/update profile
- [x] Task 3: Set up ability to delete profile / account
