### ISSUE TITLE
Report to admin

### ISSUE THREAD

**Issue by todiane** [todiane/our-spot#12]
As a user, I want to be able to report inappropriate or offensive photos or profiles  to maintain a safe and friendly community.

**Acceptance Criteria**

- [x] 1. Create report link for photos
- [x] 2. Create report link for profiles

**Tasks**

- [x] Task 1: Use bootstrap modal to add pop up box when "report photo" is clicked.
- [x] Task 2: Provide message in the box for user to click REPORT button
- [x] Task 3: Provide a success message so user knows admin has received their report.
