### ISSUE TITLE
Include example Profiles

### ISSUE THREAD

**Issue by todiane** [todiane/our-spot#19]
As admin I can add a few made up profiles to test everything is working

**Acceptance Criteria**

- [ ] 1. Create at least 7-10 profiles 
- [ ] 2. Add at least two images per profile 

**Tasks**

- [ ] Task 1: Download a variety of images from Pexels
- [ ] Task 2: Register new users using the registration form on the site
- [ ] Task 3: Test out adding, deleting, editing, viewing other photos and profiles
