### ISSUE TITLE
EPIC: User Delete Account

### ISSUE THREAD

**Issue by todiane** [todiane/our-spot#25]
As a user I can delete my account so that I can remove all details I have added to the site

**Acceptance Criteria**

- [ ] 1. User delete button

**Tasks**

- [ ] Task 1: Add delete functionality to views.py
- [ ] Task 2: Add delete button to profile page. Ensure it lets user know this is irreversible and everything will be deleted.
